font:
  normal:
    family: Roboto Mono
    style: Regular

  bold:
    family: Roboto Mono
    style: Regular

  italic:
    family: Roboto Mono
    style: Italic

  bold_italic:
    family: Roboto Mono
    style: Bold Italic

  size: 10.7
# XTerm's default colors
colors:
   # Default colors
   primary:
    background: '#000000'

window:
  padding:
    x: 10
    y: 10


      
selection:
  semantic_escape_chars: ",│`|:\"' ()[]{}<>"
