#!/bin/bash
action="$@"
brightness="$(brightnessctl | grep Current | awk '{print $4}' |  sed 's/[^0-9]*//g')"


case $action in
	up)
		if [ $brightness -lt 10 ]; then  brightnessctl set 1%+;else brightnessctl set 5%+; fi
		;;
	down)
		if [ $brightness -lt 10 ]; then  brightnessctl set 1%-;else brightnessctl set 5%-; fi
		;;		

	esac

	notify-send -u low  -h int:value:$brightness "Brightness" -t 1000 -i /usr/share/icons/elementary/status/48/brightness-display-symbolic.svg

