#!/usr/bin/bash
if pidof swayidle; then
   notify-send Caffine Enabled -t 0
   killall -9 swayidle
else
   swayidle -w timeout 30 'brightnessctl set 5%-' resume 'brightnessctl set 5%+' timeout 60 'swaymsg "output * dpms off"' resume 'swaymsg "output * dpms on"' timeout 180 'systemctl suspend' &
   makoctl dismiss

fi

