#!/bin/bash

action="$@"
volume="$(pamixer --get-volume)"

case $action in
	down)
	pamixer -d 5 > /dev/null;
	notify-send -u low \
    	-h int:value:"$volume" "Volume" -t 1000;
	;;

	up)
	pamixer -i 5 > /dev/null;
	notify-send -u low \
    	-h int:value:"$volume" "Volume" -t 1000;
	;;

	mute)
	;;
esac
