#!/bin/bash

action="$@"
volume="$(pamixer --get-volume)"

case $action in
	down)
	pamixer -d 5 > /dev/null;
	;;

	up)
	pamixer -i 5 > /dev/null;
	;;

	mute)
	;;
esac

   notify-send -u low \
  -h int:value:"$(pamixer --get-volume)" "Volume" -t 1000 -i /usr/share/icons/elementary/status/48/notification-audio-volume-high.svg
